# Generated by Django 4.1.2 on 2022-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('1', 'Food'), ('2', 'Clothes'), ('3', 'Shoes'), ('4', 'Cosmetics'), ('5', 'Sandals'), ('6', 'Bags'), ('7', 'Other')], default='1', max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='files/items')),
            ],
        ),
    ]
